-- MySQL Script generated by MySQL Workbench
-- 05/15/16 16:24:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdr_api
-- -----------------------------------------------------
-- BDR APIs

-- -----------------------------------------------------
-- Schema bdr_api
--
-- BDR APIs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdr_api` DEFAULT CHARACTER SET utf8mb4 ;
USE `bdr_api` ;

-- -----------------------------------------------------
-- Table `bdr_api`.`bdr_todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdr_api`.`bdr_todo` (
  `uuid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Contador de registros',
  `type` CHAR(20) NOT NULL,
  `content` TEXT NOT NULL,
  `sort_order` SMALLINT NULL DEFAULT 0,
  `done` TINYINT(1) NULL DEFAULT 0,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB
COMMENT = 'Lista de TODOs de um usuario visitante';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
